-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 10:08:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AnimeListo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AnimeListo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AnimeListo` DEFAULT CHARACTER SET utf8 ;
USE `AnimeListo` ;

-- -----------------------------------------------------
-- Table `AnimeListo`.`Acounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnimeListo`.`Acounts` ;

CREATE TABLE IF NOT EXISTS `AnimeListo`.`Acounts` (
  `idAcount` INT(10) GENERATED ALWAYS AS () VIRTUAL,
  `AcountName` VARCHAR(15) NOT NULL,
  `AcountPassword` VARCHAR(20) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAcount`),
  UNIQUE INDEX `idAcount_UNIQUE` (`idAcount` ASC) VISIBLE,
  UNIQUE INDEX `AcountName_UNIQUE` (`AcountName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnimeListo`.`Anime's`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnimeListo`.`Anime's` ;

CREATE TABLE IF NOT EXISTS `AnimeListo`.`Anime's` (
  `idAnime's` INT NOT NULL AUTO_INCREMENT,
  `AnimeName` VARCHAR(45) NOT NULL,
  `Describtion` VARCHAR(5000) NULL,
  `afbeelding` VARCHAR(45) NULL,
  `Seasons` INT NOT NULL,
  PRIMARY KEY (`idAnime's`),
  UNIQUE INDEX `idAnime's_UNIQUE` (`idAnime's` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AnimeListo`.`FavouriteAnimes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AnimeListo`.`FavouriteAnimes` ;

CREATE TABLE IF NOT EXISTS `AnimeListo`.`FavouriteAnimes` (
  `Acounts_idAcount` INT NOT NULL,
  `Anime's_idAnime's` INT NOT NULL,
  PRIMARY KEY (`Acounts_idAcount`, `Anime's_idAnime's`),
  INDEX `fk_Acounts_has_Anime's_Anime's1_idx` (`Anime's_idAnime's` ASC) VISIBLE,
  INDEX `fk_Acounts_has_Anime's_Acounts_idx` (`Acounts_idAcount` ASC) VISIBLE,
  CONSTRAINT `fk_Acounts_has_Anime's_Acounts`
    FOREIGN KEY (`Acounts_idAcount`)
    REFERENCES `AnimeListo`.`Acounts` (`idAcount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acounts_has_Anime's_Anime's1`
    FOREIGN KEY (`Anime's_idAnime's`)
    REFERENCES `AnimeListo`.`Anime's` (`idAnime's`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
